version: 0.0
os: windows
files:
  - source: \release
    destination: c:\inetpub\wwwroot\WontokOne_GA_PAY
hooks:
  BeforeInstall:
    - location: \StopAppPoolAndDeleteFile.ps1
  AfterInstall:
    - location: \SetupWebSite.ps1
    - location: \StartAppPool.ps1
