version: 0.0
os: windows
files:
  - source: \release
    destination: c:\inetpub\wwwroot\idSafe
hooks:
  BeforeInstall:
    - location: \StopAppPoolAndDeleteFile.ps1
  AfterInstall:
    - location: \executeps.ps1
    - location: \executepost.ps1
    - location: \StartAppPool.ps1
