version: 0.0
os: windows
files:
  - source: \release
    destination: c:\inetpub\wwwroot\WontokOne_GA_Promo
hooks:
  BeforeInstall:
    - location: \executeps.ps1
      timeout: 900
  AfterInstall:
    - location: \executepost.ps1
      timeout: 300
      runas: root